name: expense_tracker_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  phosphor_flutter: ^2.1.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  another_flushbar: ^1.12.30
  fpdart: ^1.1.0
  file_picker: ^8.0.0+1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.11
  rive_animated_icon: ^2.0.0
  flutter_carousel_widget: ^2.3.0
  grouped_list: ^6.0.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  fl_chart: ^0.70.2
  pinput: ^5.0.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#7F3DFF"
  color_dark: "#7F3DFF"
  image: "lib/assets/images/splash_center.png"

  android_12:
    color: "#7F3DFF"
    color_dark: "#7F3DFF"
    icon_background_color: "#7F3DFF"
    image: "lib/assets/images/splash_center.png"

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/

